use super::*;

pub(super) struct SkinPreviewPostProcessWgpuResources {
    pub(super) scene_pipeline: wgpu::RenderPipeline,
    pub(super) accumulate_pipeline: wgpu::RenderPipeline,
    pub(super) smaa_pipeline: wgpu::RenderPipeline,
    pub(super) fxaa_pipeline: wgpu::RenderPipeline,
    pub(super) taa_pipeline: wgpu::RenderPipeline,
    pub(super) present_pipeline: wgpu::RenderPipeline,
    pub(super) texture_bind_group_layout: wgpu::BindGroupLayout,
    pub(super) texture_sampler: wgpu::Sampler,
    pub(super) uniform_bind_group: wgpu::BindGroup,
    pub(super) uniform_buffer: wgpu::Buffer,
    pub(super) scalar_uniform_bind_group_layout: wgpu::BindGroupLayout,
    pub(super) scalar_uniform_bind_group: wgpu::BindGroup,
    pub(super) scalar_uniform_buffer: wgpu::Buffer,
    pub(super) skin_texture: Option<UploadedPreviewTexture>,
    pub(super) cape_texture: Option<UploadedPreviewTexture>,
    pub(super) accumulation_texture: wgpu::Texture,
    pub(super) accumulation_view: wgpu::TextureView,
    pub(super) accumulation_bind_group: wgpu::BindGroup,
    pub(super) scene_resolve_texture: wgpu::Texture,
    pub(super) scene_resolve_view: wgpu::TextureView,
    pub(super) scene_resolve_bind_group: wgpu::BindGroup,
    pub(super) scene_msaa_texture: Option<wgpu::Texture>,
    pub(super) scene_msaa_view: Option<wgpu::TextureView>,
    pub(super) scene_depth_texture: wgpu::Texture,
    pub(super) scene_depth_view: wgpu::TextureView,
    pub(super) post_process_texture: wgpu::Texture,
    pub(super) post_process_view: wgpu::TextureView,
    pub(super) post_process_bind_group: wgpu::BindGroup,
    pub(super) taa_history_texture: wgpu::Texture,
    pub(super) taa_history_view: wgpu::TextureView,
    pub(super) taa_history_bind_group: wgpu::BindGroup,
    pub(super) taa_history_valid: bool,
    pub(super) render_target_size: [u32; 2],
    pub(super) target_format: wgpu::TextureFormat,
    pub(super) scene_msaa_samples: u32,
    pub(super) present_msaa_samples: u32,
    pub(super) present_source: PresentSource,
}
